[package]
edition = "2021"
name = "testsuite-adaptor"
version = "0.1.0"
[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
colored = "2.0"
rayon = "1.5"
structopt = "0.3"
thiserror = "1.0"
wait-timeout = "0.2"
walkdir = "2.0"
which = "4.2"
