[package]
name = "rustc-testsuite-adaptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
thiserror = "1.0"
anyhow = "1.0"
walkdir = "2.0"
rayon = "1.5"
