name: gccrs-testing-test

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: '-Dwarnings'

jobs:
  coding-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check the coding style
      run: cargo fmt -- --check

  check:
    runs-on: ubuntu-latest
    needs: coding-style

    steps:
    - uses: actions/checkout@v2
    - name: Check testsuite-adaptor
      run: cargo check
    - name: Run Clippy
      run: cargo clippy --all -- -Wclippy::pedantic
